### ISSUE TITLE
Missing "./store" export in "svelte-google-auth" package

### ISSUE THREAD

**Issue by nick-jonas** [HalfdanJ/svelte-google-auth#14]
Seems that a `store` isn't being exported.  When I do the last step in my `+layout.svelte` file:

```
<script>
  import { signIn, signOut } from 'svelte-google-auth/client';
  import { user } from 'svelte-google-auth/store';
</script>

{$user?.name}
<button on:click={() => signIn()}>Sign In</button>
<button on:click={() => signOut()}>Sign Out</button>

```

I get the following error:

```
➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] [plugin vite:dep-scan] Missing "./store" export in "svelte-google-auth" package

    script:/Users/njonas/Code/translate-proto/src/routes/+layout.svelte?id=0:8:22:
      8 │   import { user } from 'svelte-google-auth/store';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:852:22:
      852 │         let promise = setup({
          ╵                       ^

    at setup (file:///Users/njonas/Code/translate-proto/node_modules/vite/dist/node/chunks/dep-3ffe6dd0.js:41358:19)
    at handlePlugins (/Users/njonas/Code/translate-proto/node_modules/esbuild/lib/main.js:852:23)
    at Object.buildOrServe (/Users/njonas/Code/translate-proto/node_modules/esbuild/lib/main.js:1146:7)
    at /Users/njonas/Code/translate-proto/node_modules/esbuild/lib/main.js:2103:17
    at new Promise (<anonymous>)
    at Object.build (/Users/njonas/Code/translate-proto/node_modules/esbuild/lib/main.js:2102:14)
    at build (/Users/njonas/Code/translate-proto/node_modules/esbuild/lib/main.js:1949:51)
    at file:///Users/njonas/Code/translate-proto/node_modules/vite/dist/node/chunks/dep-3ffe6dd0.js:41145:46
    at Array.map (<anonymous>)

Build failed with 1 error:
script:/Users/njonas/Code/translate-proto/src/routes/+layout.svelte?id=0:8:22: ERROR: [plugin: vite:dep-scan] Missing "./store" export in "svelte-google-auth" package
__vite_ssr_import_0__.redirect is not a function
TypeError: __vite_ssr_import_0__.redirect is not a function
    at load (/src/routes/+layout.server.js:8:8)
    at load_server_data (file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:41)
    at file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:177:19
__vite_ssr_import_0__.redirect is not a function
TypeError: __vite_ssr_import_0__.redirect is not a function
    at load (/src/routes/+layout.server.js:8:8)
    at load_server_data (file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:41)
    at respond_with_error (file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:37:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/index.js:317:12)
    at async SvelteGoogleAuthHook.handleAuth (file:///Users/njonas/Code/translate-proto/node_modules/svelte-google-auth/server.js:89:16)
    at async Object.handle (//Users/njonas/Code/translate-proto/src/hooks:10:9)
    at async respond (file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/runtime/server/index.js:341:10)
    at async file:///Users/njonas/Code/translate-proto/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:376:22
```

**Comment by HalfdanJ** [comment]
Yeah sorry, i had to remove that again, but forgot it in the readme. Removing the reference in https://github.com/HalfdanJ/svelte-google-auth/pull/15. 

You can do `{data.auth.user?.name}` instead
